# 1
  a
# 2
  b
# 3
    a \
  ||
    b \
  ||
    c \
  ||
    d \
  ||
    e
# 4
    a \
  &&
    b \
  &&
      c \
    |
      d \
  &&
    e \
  &&
    f
# 5
      echo lol \
    |
      cat>foo.txt \
  &&
    echo ok \
  &&
    ls
# 6
        cat<bar.txt \
      ||
        ls \
    &&
      pwd \
  ||
    echo what
# 7
    a \
  &&
    b \
  &&
    c \
  &&
    d
# 8
      (
         ls \
       ;
         cat>foo.txt
      )>out.txt \
    &&
      echo ok \
  ||
    echo what
# 9
    (
         ls \
       &&
         pwd \
       &&
           a>b \
         |
           c<d \
     ;
       cat>foo.txt
    )<in.txt \
  ||
    echo abc \
  ||
    echo def
# 10
    a \
  &&
    b \
  &&
      c \
    |
      (
           d \
         &&
           e \
       ;
         f
      ) \
  &&
    g
# 11
  (
   a
  )>b
# 12
  (
       a \
     &&
         b \
       |
         (
              c \
            ||
              d \
          ;
            e
         )>f \
   ;
       g \
     ||
       h
  )<i
